# Generated by Django 5.1.6 on 2025-03-02 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=50)),
                ('execution_time', models.FloatField(help_text='Time taken in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='APIErrorLog',
        ),
        migrations.DeleteModel(
            name='FraudDetectionLog',
        ),
        migrations.DeleteModel(
            name='ServerPerformance',
        ),
        migrations.AlterField(
            model_name='activeuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='response_time',
            field=models.FloatField(help_text='Time taken in milliseconds'),
        ),
        migrations.AlterField(
            model_name='modelperformance',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
